class CharacterClass(object):
    def __init__(self):
        self.name = None

# TODO THIS SHOULD HAVE A LEVEL TREE THAT GRANTS BONUSES, CHARACTER WOULD KEEP THE REFERENCE TO THE CLASS
# BUT NEEDS AN ACTUAL LEVEL ID TO GRAB ALL BONUSES OF THE LOWER BRANCHES AND THE TOP ONE
